services:
  - type: web
    name: painel-dropcolab
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: seu_token_telegram
      - key: CHAT_ID
        value: 7092570800
      - key: DROPBOX_TOKEN
        value: seu_token_dropbox
      - key: RPC_SECRET
        value: teste123
